name: Build And Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test Driver
    runs-on: ubuntu-latest                # keep your own runner
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # ──────────────────────────────────────────────────────────
      # Dependency install — handle old & new Pythons differently
      # ──────────────────────────────────────────────────────────
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install flake8 codacy-coverage
            python -m pip install -U -r requirements.txt -r test-requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Tests
        run: python -m pytest
